### ISSUE TITLE
[RFC]: react:no-useless-fragment

### ISSUE THREAD

**Issue by pierrezimmermannbam** [bamlab/react-native-project-config#63]
### Why?

Cette règle supprime tous les fragments qui ne wrapent qu'un élément. Peut s'autofix. C'est pratique pour la refacto, c'est toujours cool d'enlever un niveau de nesting. Je ne vois aucun inconvénient à l'utilisation de cette règle  

### Rule Documentation 📜

https://github.com/jsx-eslint/eslint-plugin-react/blob/master/docs/rules/jsx-no-useless-fragment.md

### Config Selection 🛠

`recommended`

**Comment by MattAgn** [comment]
Chaud pour l'ajouter !

**Comment by charlotteisambert** [comment]
Validée
