### ISSUE TITLE
[RFC]: remove import/namespace rule

### ISSUE THREAD

**Issue by pierrezimmermannbam** [bamlab/react-native-project-config#64]
### Why?

Si je check le temps d'exécution du lint sur mon projet j'ai le résultat suivant:

<img width="413" alt="Capture d’écran 2023-09-22 à 14 30 18" src="https://github.com/bamlab/react-native-project-config/assets/64224599/fb06fcb8-7837-4666-bbe9-ab99f141c824">

Cette règle prend un tiers du temps de lint, plus que prettier !

Surtout, elle me parait inutile si on utilise typescript. Si j'essaye de faire ce que la règle interdit, j'ai une erreur ts

![Capture d’écran 2023-09-22 à 14 29 21](https://github.com/bamlab/react-native-project-config/assets/64224599/ffe703d0-edb5-4bcd-8f83-8e54f95f803d)

Si elle est couteuse est peu utile, on peut la désactiver

### Rule Documentation 📜

https://github.com/import-js/eslint-plugin-import/blob/main/docs/rules/namespace.md

### Config Selection 🛠

`recommended`

**Comment by matthieugicquel** [comment]
Y a des fortes chances que la mesure du temps soit biaisée parce que c'est la 1ère règle de eslint-plugin-import qui est appliquée... T'as mesuré la diff de temps quand tu la retire ?

**Comment by charlotteisambert** [comment]
A tester : si on enlève la règle, est ce que le temps n'est quand même pas le même ? hypothèse : la première règle est plus longue à cause de la mise en route

**Comment by pierrezimmermannbam** [comment]
Il semblerait que ça ne prenne quasiment pas de temps finalement, autant garder la règle pour ne pas alourdir la config dans ce cas
