### ISSUE TITLE
[RFC]: @typescript-eslint/no-floating-promises

### ISSUE THREAD

**Issue by EveJulliard** [bamlab/react-native-project-config#67]
### Why?

Cette règle permet de s'assurer qu'on await bien toutes les promesses.

### Rule Documentation 📜

https://typescript-eslint.io/rules/no-floating-promises/

### Config Selection 🛠

`recommended`

**Comment by robingullo** [comment]
Avec cette règle, si on veut explicitement ne pas attendre une promesse, il faut utiliser le mot clé `void` mais il y a une règle lint `no-void` qui peut faire un conflit avec ça. Tu pourrais tester avec la config actuelle (elle peut être dans un preset) ? Si elle y est il faudrait l'autoriser avec l'option `allowAsStatement`
https://typescript-eslint.io/rules/no-floating-promises/#ignorevoid
https://eslint.org/docs/latest/rules/no-void#allowasstatement

**Comment by charlotteisambert** [comment]
Reco Matthieu G : mettre autofix pour forcer les personnes à ignorer la règle s'ils veulent pas attendre

TODO : @charlotteisambert  check qu'il n'y a pas de conflits avec d'autres règles
